### PR TITLE
AMO API

### PR DESCRIPTION
**Pull request by commuterjoy**
Basic outline of an API to accept an IP address and send back the AMO response.

/cc @ifyio

### CODE REVIEW

**Comment by ifyio** [comment]
Hi Matt can you explain the motivation a bit?

**Comment by ifyio** [comment]
Ok. From what I can gather, the plan is to hit this API and it's this API that would handle retrieving the amo data by ip. That way, the message prompts js client wont have to know the ip. Am I correct?

**Comment by commuterjoy** [comment]
Yep.

So browser hits this API, the API extracts the IP address from the header, forwards it to the AMO service, which responds, then we map that response to a message.

Over time the propensity API will model all sorts of factors (see the doc I just shared with you) and make a decision on what message to show a user.

**Comment by ifyio** [comment]
Makes sense. Will this api also be the one making the decisions? Meaning, will return view specific data or will it just be a generic api that clients consume and decide what to do based on the returned data?

**Comment by commuterjoy** [comment]
> Will this api also be the one making the decisions?

I think so. Because we want to eliminate lots of clients sending lots of different messages to people.

**Pull request merged**
