### PR TITLE
Compare a given piece of content to hot topics

### PR DESCRIPTION
**Pull request by commuterjoy**
Essentially the intersection of the tags associated with a piece content (from CAPI) and the tags in the Popular API.

Hi @ifyio - I wasn't around today much but I did get a chance to have a quick go at this.

I've split the 'top brands' and 'popular topics' in to two separate cohorts, and joined them together in the topically-interested propensity. So the propensity is currently matched if you find a Volkswagen story in Lex, for example.

### CODE REVIEW

**Comment by commuterjoy** [comment]
also, merge conflict is on 

 server/resources/propensity/propensities/topically-interested.js

... which you removed, so let me know what you want to do with that.

**Comment by commuterjoy** [comment]
PS. not at work tomorrow.

**Comment by ifyio** [comment]
Hi @commuterjoy - Yes I renamed `topically-interested.js` to 'top-reader.js' as in `TopReaderPropensity` and I used your previous implementation of the cohort as the basis for implementing a new `TopBrandCohort`. I figured these names were simpler and more representative. I wanted to discuss some things with you. For the message, I needed to get the primary theme and so I called a different capi endpoint that would also get me the primary theme. I will also have a look at what you have done here and integrate it the propensity branch.

**Comment by commuterjoy** [comment]
old!

**Pull request closed without merging**
